apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    run: simple-webapp
spec:
  containers:
  - name: web-app
    image: web-app
    ports:
      - containerPort: 8080
    livenessProbe:
      # you should specify only one handler type: http / tcp / exec command
      # HTTP Test
      httpGet:
        path: /api/healthy
        port: 8080
      # TCP Test
      tcpSocket:
        port: 3306
      # Exec Command
      exec:
        command:
          - cat
          - /app/is_healthy
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 8