apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  # security context at the pod level
  securityContext:
    runAsUser: 1000
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]
    # security context at the pod level

