apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    run: simple-webapp
spec:
  containers:
  - name: web-app
    image: web-app
    ports:
      - containerPort: 8080
  initContainers:
  - name: log-shipper
    image: busybox
    command: 'setup-log-shipper.sh'
    restartPolicy: Always
